# Configuration for memory allocation and addressing
memory:
  # Configuration related to memory allocation
  allocation:
    # Path to the mounted hugepages filesystem
    hugepages_mount: /path/to/hugepages/mounted
    # Amount of memory in bytes to allocate
    size_bytes: 1073741824

# Configuration specific to the DRAM module and its layout
dram:
  # DRAM addressing layout configuration
  layout:
    # List of functions for address mapping
    addressing_functions:
      - 0x2040
      - 0x24000
      - 0x48000
      - 0x90000
    # Mask to filter out the rows in the physical address
    row_mask: 0xffffe0000
    # Mask to filter out the columns in the physical address
    col_mask: 0x1FFF

# Strategy for translating virtual to physical addresses
physical_translation:
  selfmap:
    pagemap_path: /proc/self/pagemap
    page_size: 4096  # bytes
    pagemap_entry_size: 8  # bytes
    pfn_mask: 0x7FFFFFFFFFFFFF  # hex mask for bits 0 to 54 inclusive
    page_present_mask: 0x8000000000000000  # hex mask for bit 63
  # Or alternatively
  # hypercall:
  #   hypercall_number: 14

# Configuration related to the hammering process
hammering:
  # Number of rounds for hammering
  rounds: 1000000
  # Offset from the beginning of the contiguous chunk
  base_offset: 0
  # Length of the hammer pattern
  pattern_length: 1024
  # Strategy for generating data to be hammered
  hammer_data: Random
  # Strategy to access memory during hammering
  memory_access_strategy:
    strategy: native
  # If you want the hypervisor to assist with some of the memory accesses,
  # specify the percentage of accesses for hypervisor assistance.
  # hypervisorAssistance:
  #   percentage: 20  # e.g., hypervisor assists with 20% of the accesses
